---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queries
  labels:
    app: queries
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queries
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
  template:
    metadata:
      labels:
        app: queries
    spec:
      containers:
        - name: queries
          image: alejomantilla/queries
          ports:
            - containerPort: 5001
          envFrom:
            - configMapRef:
                name: auth-configmap
            - secretRef:
                name: auth-secret
