---
# This is a basic workflow to help you get started with Actions
name: Build and publish docs
# Controls when the action will run.
on:
  # Triggers the workflow on push (A push gets triggered also when a Pull Request is merged)
  # events but only for the main branch
  push:
    branches: [main]
    paths:
      - docs/**
      - .github/workflows/build_docs.yml

  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:
# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
# Allow one concurrent deployment. New triggered workflows will interrupt on other concurrent ones
concurrency:
  group: pages
  cancel-in-progress: true
# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    name: Install dependencies, build, and deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # Checkout this repo
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Install python and book build dependencies
      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ./docs/requirements.yml
          environment-name: JBookEnv
          cache-environment: true

      # Build the book, requires bash to initialize autorun scripts for mamba, hence bash -el {0}
      - name: Build the book
        shell: bash -el {0}
        run: |
          jupyter-book build --all ./docs/book_contents
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload repo subdirectory
          path: ./docs/book_contents/_build/html/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
